  name: CodadoCore
  main: br.com.codadocode.codadocore.CodadoCore
  version: 0.1
  api-version: 1.19
  commands:
    setspawn:
      description: Set world spawn origin point.
      usage: /setspawn
      permission: br.com.codadocode.codadocore.setspawn
    spawn:
      description: Teleport to spawn point
      usage: /spawn
      permission: br.com.codadocode.codadocore.spawn
    areacreate:
      description: Create new area
      usage: /areacreate
      permission: br.com.codadocode.codadocore.areacreate
    areainfo:
      description: Show are info
      usage: /areainfo
      permission: br.com.codadocode.codadocore.areainfo
    areasetowner:
      description: Set owner area
      usage: /areasetowner
      permission: br.com.codadocode.codadocore.areasetowner